name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests on PHP ${{ matrix.php }}${{ matrix.name_suffix }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t package --build-arg PHP_VERSION=${{ matrix.php }} .

      - name: Run tests
        run: docker run package vendor/bin/phpunit

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t package .

      - name: Run phpstan
        run: docker run package vendor/bin/phpstan analyse --memory-limit=1G
